name: Run Rust Coverage

on:
  pull_request:
    branches: [ develop ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain (+llvm-tools-preview)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Run cargo llvm-cov
        run: cargo llvm-cov --package ieee1905 --summary-only --output-path coverage_report.txt

      - name: Generate Coverage Report
        id: coverage_report
        run: |
          cargo llvm-cov report > coverage_output.txt
          echo "COVERAGE_DATA<<EOF" >> $GITHUB_ENV
          cat coverage_output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post Coverage Report Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage-report
          path: coverage_report.txt
